Agregando gra6-uni6-lec3 sin traducciones
enriqueacosta/IllustrativeMath-GrupoLEMA pull request #119
Opened 2024-12-11 02:55 UTC by oterpater

2024-12-11 15:40 UTC, enriqueacosta commented
@oterpater , se ve genial, pero creo que mejor hacer unas cosas antes de que hagamos merge:
*  resolver los comentarios que dejé.
* Agregar [@@@@@@@] a todos los textos que siguen en ENG (cómo mínimo al puro inicio de un texto que siga en ENG).
* agregar las sols de los PPs.

Gracias!

2024-12-11 15:42 UTC, enriqueacosta requested changes

2024-12-11 15:42 UTC, enriqueacosta commented on source/gra6-uni6/lec-mantenerBalance.ptx
> +</objectives>
los objetivos adentro de `<objectives>` deben ir en un `<ul>` (de lo contrario son ignorados, como lo están siendo ahora).

2024-12-11 15:42 UTC, enriqueacosta commented on source/gra6-uni6/warm-enganchados.ptx
> +
Imagen muy grande. Hay que reducir el width.

2024-12-11 16:08 UTC, enriqueacosta commented on source/gra6-uni6/gra6-uni6-secA-lec1-PPalign1.ptx
(es un caso especial, porque el `.ptx` de la lec1 ya existe)

2024-12-17 00:54 UTC, oterpater commented on source/gra6-uni6/gra6-uni6-secA-lec1-PPalign1.ptx
> +</statement>
No entendí!

2024-12-17 01:22 UTC, enriqueacosta commented on source/gra6-uni6/gra6-uni6-secA-lec1-PPalign1.ptx
> +</statement>
@oterpater , que esto se ve muy distinto al original. El "layout" es distinto. Mejor seguir el original (no por seguirlo, sino porque es un layout menos complejo).

2024-12-17 15:11 UTC, oterpater commented on source/gra6-uni6/warm-enganchados.ptx
> +
De acuerdo, en este commit no le presté atención a las imágenes, solo a la ingestión.

2024-12-17 15:11 UTC, oterpater commented on source/gra6-uni6/cool-pesoCirculo.ptx
> +<title>El perso del círculo</title>
Upps!

2024-12-17 15:13 UTC, oterpater commented on source/gra6-uni6/cool-pesoCirculo.ptx
> +</statement>
De acuerdo. Aproveché y dejé espacio entre columnas.

2024-12-17 15:13 UTC, oterpater commented on source/gra6-uni6/cool-pesoCirculo.ptx
> +<statement>
No lo encuentro en los archivos que me enviaste. Dónde crees que están?

2024-12-17 15:13 UTC, oterpater commented on source/gra6-uni6/lec-mantenerBalance-PP1.ptx
> +    Selecciona **todas** las ecuaciones que representen el colgador.
Esooo! No di con cuál era la forma, lo he usado antes.

2024-12-17 15:14 UTC, oterpater commented on source/gra6-uni6/lec-mantenerBalance-PP1.ptx
> +
De acuerdo! Corregido

2024-12-17 15:14 UTC, oterpater commented on source/gra6-uni6/lec-mantenerBalance-PP4.ptx
> +  <sidebyside widths="40% 60%" valign="top">
Aquí funcionó haciendo la columna de la imagen más pequeña. Además, dejé el espacio entre columnas

2024-12-17 15:15 UTC, oterpater commented on source/gra6-uni6/gra6-uni6-secA-lec1-PPalign1.ptx
> +</statement>
Ya vimos que la versión en español del estudiante está distinto a la versión en inglés del profesor. Igual se realizó el cambio!

2024-12-17 15:15 UTC, oterpater commented on source/gra6-uni6/gra6-uni6-secA-lec1-PPalign1.ptx
Lo pensé pero no estaba segura de hacer ese cambio, pues los demás quedaron con los números. Hice el cambio

2024-12-17 15:47 UTC, enriqueacosta requested changes
@oterpater , va muy bien!

Quedan unos comments pendientes de resolver, y falta el cool en ESP.

Gracia!

2024-12-17 15:47 UTC, enriqueacosta commented on source/gra6-uni6/lec-mantenerBalance.ptx
> +</objectives>
@oterpater , creo que hay que poner el @@@@@@ adentro de un `<li>` para que pretext no lo ignore.

2024-12-17 15:47 UTC, enriqueacosta commented on source/gra6-uni6/warm-enganchados.ptx
> +
pero en ingestión los tamaños de imágenes tienen que quedar bien.

2024-12-17 15:47 UTC, enriqueacosta commented on source/gra6-uni6/cool-pesoCirculo.ptx
> +<statement>
Chat de google.

2024-12-17 15:47 UTC, enriqueacosta commented on source/gra6-uni6/lec-mantenerBalance-resumen.ptx
> +
@oterpater , ¿si ajustaste este?

2024-12-17 15:47 UTC, enriqueacosta commented on source/gra6-uni6/lec-mantenerBalance-PP4.ptx
> +  <sidebyside widths="40% 60%" valign="top">
se ve súper.

2024-12-17 15:47 UTC, enriqueacosta commented on source/gra6-uni6/lec-diagramasCintaYEcuaciones-PPalign1.ptx
> +  <image source="png-source/6-6.6.PP.msand12s.png" width="80%">
mejor 100% en este caso

2024-12-17 15:47 UTC, enriqueacosta commented on source/gra6-uni6/gra6-uni6-secA-lec1-PPalign1.ptx
> +</statement>
si. mucho mejor!

2024-12-17 15:55 UTC, oterpater commented on source/gra6-uni6/cool-pesoCirculo.ptx
> +<statement>
Listo! Revisado y reemplazado por la versión en español

2024-12-17 15:56 UTC, oterpater commented on source/gra6-uni6/lec-mantenerBalance-PP1.ptx
> +    A,C
De acuerdo!

2024-12-17 15:57 UTC, oterpater commented on source/gra6-uni6/lec-diagramasCintaYEcuaciones-PPalign1.ptx
> +  <image source="png-source/6-6.6.PP.msand12s.png" width="80%">
Ok!

2024-12-17 15:59 UTC, oterpater commented on source/gra6-uni6/lec-mantenerBalance.ptx
> +</objectives>
Corregido!

2024-12-17 16:06 UTC, oterpater commented on source/gra6-uni6/gra6-uni3-secD-lec11-PPalign3.ptx
> +</solution>
Revisar https://github.com/enriqueacosta/IllustrativeMath-GrupoLEMA/issues/120

2024-12-17 16:36 UTC, enriqueacosta commented
Hago el merge! Gracias @oterpater !

2024-12-17 16:36 UTC, merged