paso B gra3 uni4 lec7
enriqueacosta/IllustrativeMath-GrupoLEMA pull request #141
Opened 2024-12-29 18:15 UTC by veronicamariGNo

2025-01-03 05:07 UTC, enriqueacosta requested changes
Se ve genial @veronicamariGNo ! Pero mejor que haga unos ajustes antes de que hagamos el merge. ¿Puede revisar porfa los ajustes que le dejé?

2025-01-03 05:07 UTC, enriqueacosta commented on source/gra3-uni4/warm-cuantosVes-decenas.ptx
>      <li>Veo 6 grupos de 10.</li>
justo encima de esta frase hay un [sample responses] que sigue en ENG!

2025-01-03 05:07 UTC, enriqueacosta commented on source/gra3-uni4/warm-cuantosVes-decenas.ptx
> +    <p>Cuando los estudiantes utilizan la agrupación para encontrar el total en un múltiplo de diez, buscan y hacen uso de estructuras.</p>
El último ajuste va en contra de GLO:
>MP7. Look for and make use of structure.

--->

> PM7. Buscar y hacer uso de estructuras

2025-01-03 05:07 UTC, enriqueacosta commented on source/gra3-uni4/warm-numTalk-multiplicacionYDivision.ptx
> +    <p>Cuando los estudiantes utilizan la relación entre la multiplicación y la división para encontrar hechos de división que no conocen, están buscando y haciendo uso de estructuras (MP7).</p>
El último ajuste va en contra de GLO:

>MP7. Look for and make use of structure.

--->

>PM7. Buscar y hacer uso de estructuras

2025-01-05 13:51 UTC, veronicamariGNo commented on source/gra3-uni4/act-clasificacionDeTarjetas-multiplicacion.ptx
> +      <li>Dé a cada grupo un grupo de tarjetas previamente recortadas y una tabla de clasificación.
De acuerdo!

2025-01-05 13:52 UTC, veronicamariGNo commented on source/gra3-uni4/act-clasificacionDeTarjetas-multiplicacion.ptx
> +      <li>1 minuto: tiempo de trabajo inddividual</li>
iCorregido!

2025-01-05 13:54 UTC, veronicamariGNo commented on source/gra3-uni4/lec-relacionarMultiplicacionYDivision.ptx
> +  <p><q>¿Cómo se relacionan?</q> (El número desconocido en la ecuación de división (el cociente) es el número de grupos o el número en cada grupo y eso es lo que representa el número desconocido en l
Lo cambié por ", es decir el cociente,".

2025-01-05 13:55 UTC, veronicamariGNo commented on source/gra3-uni4/warm-cuantosVes-decenas.ptx
>      <li>Veo 6 grupos de 10.</li>
Uy! Corregido!

2025-01-05 13:58 UTC, veronicamariGNo commented on source/gra3-uni4/warm-cuantosVes-decenas.ptx
> +    <p>Cuando los estudiantes utilizan la agrupación para encontrar el total en un múltiplo de diez, buscan y hacen uso de estructuras.</p>
Estoy confundida. Yo hice el cambio porque busqué en GLO. Busque "grouping" y salen varias entradas y en todas se usa "agrupación".

2025-01-05 13:59 UTC, veronicamariGNo commented on source/gra3-uni4/warm-numTalk-multiplicacionYDivision.ptx
> +    <p>Cuando los estudiantes utilizan la relación entre la multiplicación y la división para encontrar hechos de división que no conocen, están buscando y haciendo uso de estructuras (MP7).</p>
No le entiendo... Precisamente eso hice, no?

2025-01-05 16:39 UTC, enriqueacosta commented on source/gra3-uni4/warm-cuantosVes-decenas.ptx
> +    <p>Cuando los estudiantes utilizan la agrupación para encontrar el total en un múltiplo de diez, buscan y hacen uso de estructuras.</p>
My comentario es sobre lo que sigue después de la coma. Cambió [ buscan y hacen uso de la estructura] por [buscan y hacen uso de estructuras] y eso no se alinea con GLO (y también me parece que le cambia el sentido). No son "estructuras" sino "la estructura"...

2025-01-05 16:40 UTC, enriqueacosta commented on source/gra3-uni4/warm-numTalk-multiplicacionYDivision.ptx
> +    <p>Cuando los estudiantes utilizan la relación entre la multiplicación y la división para encontrar hechos de división que no conocen, están buscando y haciendo uso de estructuras (MP7).</p>
@veronicamariGNo , tiene toda la razón! Sorry!

2025-01-09 17:34 UTC, enriqueacosta reviewed
Se ve súper! 

Le dejé unos comentarios en una parte en la que me parece que está sugiriendo cambiar los encabezados de una tabla. Si estoy en lo cierto le ayudaría a hacer la tabla antes de que hagamos el merge.

2025-01-09 17:34 UTC, enriqueacosta commented on source/gra3-uni4/act-siSeQueEntoncesSeQueMult.ptx
> +        <shortdescription>Tabla, dos columnas. Encabezados: Columna 1 "Si me sé....", Columna 2 "Entonces me sé...". Primera columna debajo del encabezado con filas con productos 2 por 24, 3 por 5, 4
Pero entonces, ¿está sugiriendo que cambiemos el encabezado de la tabla misma?

Si sí, nos toca re-generar la tabla y el BLM asociado (yo le ayudaría con esa parte).

2025-01-09 17:34 UTC, enriqueacosta commented on source/gra3-uni4/act-siSeQueEntoncesSeQueMult.ptx
> +        <shortdescription>Tabla, dos columnas. Encabezados: Columna 1 "Si me sé....", Columna 2 "Entonces me sé...". Primera columna debajo del encabezado con filas con productos 2 por 24, 3 por 5, 4
Pero entonces, ¿está sugiriendo que cambiemos el encabezado de la tabla misma? 

Si sí, nos toca re-generar la tabla y el BLM asociado (yo le ayudaría con esa parte).

2025-01-09 17:34 UTC, enriqueacosta commented on source/gra3-uni4/act-siSeQueEntoncesSeQueMult.ptx
> +        <shortdescription>Tabla, dos columnas. Encabezados: Columna 1 "Si me sé....", Columna 2 "Entonces me sé...". Primera columna debajo del encabezado con filas con productos 2 por 24, 3 por 5, 4
Pero entonces, ¿está sugiriendo que cambiemos el encabezado de la tabla misma?

Si sí, nos toca re-generar la tabla y el BLM asociado (yo le ayudaría con esa parte).

2025-01-14 19:25 UTC, veronicamariGNo commented on source/gra3-uni4/warm-cuantosVes-decenas.ptx
> +    <p>Cuando los estudiantes utilizan la agrupación para encontrar el total en un múltiplo de diez, buscan y hacen uso de estructuras.</p>
Listo... y ya revisé y usted dejó agrupación... todo bien.

2025-01-14 19:26 UTC, veronicamariGNo commented on source/gra3-uni4/act-siSeQueEntoncesSeQueMult.ptx
> +        <shortdescription>Tabla, dos columnas. Encabezados: Columna 1 "Si me sé....", Columna 2 "Entonces me sé...". Primera columna debajo del encabezado con filas con productos 2 por 24, 3 por 5, 4
Ya está esto en un ISSUE.

2025-01-14 19:26 UTC, veronicamariGNo commented on source/gra3-uni4/act-siSeQueEntoncesSeQueMult.ptx
> +        <shortdescription>Tabla, dos columnas. Encabezados: Columna 1 "Si me sé....", Columna 2 "Entonces me sé...". Primera columna debajo del encabezado con filas con productos 2 por 24, 3 por 5, 4
Ya está esto en un ISSUE.

2025-01-14 19:26 UTC, veronicamariGNo commented on source/gra3-uni4/act-siSeQueEntoncesSeQueMult.ptx
> +        <shortdescription>Tabla, dos columnas. Encabezados: Columna 1 "Si me sé....", Columna 2 "Entonces me sé...". Primera columna debajo del encabezado con filas con productos 2 por 24, 3 por 5, 4
Ya está esto en un ISSUE.

2025-01-14 19:34 UTC, veronicamariGNo commented
Tengo problemas con esto... Podemos hablar?
Verónica
________________________________
De: Enrique Acosta ***@***.***>
Enviado: domingo, 5 de enero de 2025 11:40 a. m.
Para: enriqueacosta/IllustrativeMath-GrupoLEMA ***@***.***>
Cc: veronicamariGNo ***@***.***>; Mention ***@***.***>
Asunto: Re: [enriqueacosta/IllustrativeMath-GrupoLEMA] paso B gra3 uni4 lec7 y lec 8 (PR #141)


@enriqueacosta commented on this pull request.

________________________________

In source/gra3-uni4/warm-cuantosVes-decenas.ptx<https://github.com/enriqueacosta/IllustrativeMath-GrupoLEMA/pull/141#discussion_r1903304061>:

>
-    <p>Cuando los estudiantes utilizan el agrupamiento para encontrar el total en un múltiplo de diez, buscan y hacen uso de la estructura.</p>
+    <p>Cuando los estudiantes utilizan la agrupación para encontrar el total en un múltiplo de diez, buscan y hacen uso de estructuras.</p>


@veronicamariGNo<https://github.com/veronicamariGNo> , my comentario es sobre lo que sigue después de la coma. Cambió [ buscan y hacen uso de la estructura] por [buscan y hacen uso de estructuras] y eso no se alinea con GLO (y también me parece que le cambia el sentido). No son "estructuras" sino "la estructura"...

—
Reply to this email directly, view it on GitHub<https://github.com/enriqueacosta/IllustrativeMath-GrupoLEMA/pull/141#discussion_r1903304061>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BNSKSVDABRVVWNL43SF7TZT2JFN7RAVCNFSM6AAAAABULAPPDOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMZQHEZTCNZRGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-01-14 19:34 UTC, veronicamariGNo commented on source/gra3-uni4/warm-numTalk-multiplicacionYDivision.ptx
> +    <p>Cuando los estudiantes utilizan la relación entre la multiplicación y la división para encontrar hechos de división que no conocen, están buscando y haciendo uso de estructuras (MP7).</p>
Ok

2025-01-14 19:35 UTC, veronicamariGNo commented
No hace falta... en su siguiente correo me dijo que yo tenía razón...
________________________________
De: Verónica Mariño Salazar ***@***.***>
Enviado: martes, 14 de enero de 2025 2:34 p. m.
Para: enriqueacosta/IllustrativeMath-GrupoLEMA ***@***.***>; enriqueacosta/IllustrativeMath-GrupoLEMA ***@***.***>
Cc: Mention ***@***.***>
Asunto: RE: [enriqueacosta/IllustrativeMath-GrupoLEMA] paso B gra3 uni4 lec7 y lec 8 (PR #141)

Tengo problemas con esto... Podemos hablar?
Verónica
________________________________
De: Enrique Acosta ***@***.***>
Enviado: domingo, 5 de enero de 2025 11:40 a. m.
Para: enriqueacosta/IllustrativeMath-GrupoLEMA ***@***.***>
Cc: veronicamariGNo ***@***.***>; Mention ***@***.***>
Asunto: Re: [enriqueacosta/IllustrativeMath-GrupoLEMA] paso B gra3 uni4 lec7 y lec 8 (PR #141)


@enriqueacosta commented on this pull request.

________________________________

In source/gra3-uni4/warm-cuantosVes-decenas.ptx<https://github.com/enriqueacosta/IllustrativeMath-GrupoLEMA/pull/141#discussion_r1903304061>:

>
-    <p>Cuando los estudiantes utilizan el agrupamiento para encontrar el total en un múltiplo de diez, buscan y hacen uso de la estructura.</p>
+    <p>Cuando los estudiantes utilizan la agrupación para encontrar el total en un múltiplo de diez, buscan y hacen uso de estructuras.</p>


@veronicamariGNo<https://github.com/veronicamariGNo> , my comentario es sobre lo que sigue después de la coma. Cambió [ buscan y hacen uso de la estructura] por [buscan y hacen uso de estructuras] y eso no se alinea con GLO (y también me parece que le cambia el sentido). No son "estructuras" sino "la estructura"...

—
Reply to this email directly, view it on GitHub<https://github.com/enriqueacosta/IllustrativeMath-GrupoLEMA/pull/141#discussion_r1903304061>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BNSKSVDABRVVWNL43SF7TZT2JFN7RAVCNFSM6AAAAABULAPPDOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMZQHEZTCNZRGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-01-14 19:55 UTC, enriqueacosta commented on source/gra3-uni4/act-siSeQueEntoncesSeQueMult.ptx
> +        <shortdescription>Tabla, dos columnas. Encabezados: Columna 1 "Si me sé....", Columna 2 "Entonces me sé...". Primera columna debajo del encabezado con filas con productos 2 por 24, 3 por 5, 4
Gracias @veronicamariGNo ! Me encargo cuando hagamos el merge!

2025-01-14 19:55 UTC, enriqueacosta commented on source/gra3-uni4/act-siSeQueEntoncesSeQueMult.ptx
> +        <shortdescription>Tabla, dos columnas. Encabezados: Columna 1 "Si me sé....", Columna 2 "Entonces me sé...". Primera columna debajo del encabezado con filas con productos 2 por 24, 3 por 5, 4
Gracias @veronicamariGNo ! Me encargo cuando hagamos el merge!

2025-01-14 21:04 UTC, merged