gra0-uni1-secC-lec11 ya esta terminada
enriqueacosta/IllustrativeMath-GrupoLEMA pull request #25
Opened 2023-11-14 21:57 UTC by jonathandefe

2023-11-14 21:57 UTC, jonathandefe commented
tramajo conpleto

2023-11-14 21:57 UTC, jonathandefe commented
trabajo completo

2023-11-14 22:43 UTC, enriqueacosta commented
@jonathandefe , varios comentarios. Por favor ajústalos y vuelve a hacer el pull request:
*  No agregaste la lección 11 para que sea visible. Eso lo debe hacer en el archivo `gra0-uni1.ptx`. Mira la linea 138 de ese archivo.
* Falta el título en la lección 11. Está con `[@@@@@@@@@]`
* La imagen en la actividad `gra0-uni1-secC-lec11-act2` se ve muy pequeña. Revisa el `width=`
* Pusiste algo en el cool, pero en esta lección no hay. Porfa el archivo de TEMPLATES en el archivo `gra0-uni1-secC-lec11-cool.ptx` deja lo que tiene el TEMPLATE `TEMPLATES/graVV-uniXX-secYY-lecZZ-cool.ptx`

2023-11-14 22:45 UTC, enriqueacosta requested changes
@jonathandefe , varios comentarios. Por favor ajústalos y vuelve a hacer el pull request:

No agregaste la lección 11 para que sea visible. Eso lo debe hacer en el archivo gra0-uni1.ptx. Mira la linea 138 de ese archivo.
Falta el título en la lección 11. Está con [@@@@@@@@@]
La imagen en la actividad gra0-uni1-secC-lec11-act2 se ve muy pequeña. Revisa el width=
Pusiste algo en el cool, pero en esta lección no hay. Porfa el archivo de TEMPLATES en el archivo gra0-uni1-secC-lec11-cool.ptx deja lo que tiene el TEMPLATE TEMPLATES/graVV-uniXX-secYY-lecZZ-cool.ptx

2023-11-28 20:23 UTC, jonathandefe commented
ya están listos los cambios

2023-11-28 20:24 UTC, merged