Avances Lección 3.4.D.20
enriqueacosta/IllustrativeMath-GrupoLEMA pull request #77
Opened 2024-09-24 20:14 UTC by aguilulfo

Sorry, ahora sí!

2024-09-24 20:50 UTC, enriqueacosta commented
@aguilulfo , esta es la versión definitiva de paso A de esta lección? O solo son avances? Pregunto para saber is hacer una revisión general, o solo de avances.

2024-09-24 20:57 UTC, enriqueacosta requested changes
Se ve genial @aguilulfo . Van unos comentarios a las adiciones de código que veo. No es una revisión global de toda la lección.

Me espero a sus ajustes para hacer el merge.

Gracias!

2024-09-24 20:57 UTC, enriqueacosta commented on source/gra3-uni4/gra3-uni4-secD-lec20-act3-mat.ptx
> +<li>Compara, Etapa 4 (Tarjetas de división) </li>
@aguilulfo , sugiero que deje acá unos @@@, como mecanismo para que sepamos que falta algo. ¿de pronto así? ¿o se le ocurre algo mejor?
```xml
<li>Compara, Etapa 4 (Tarjetas de división) @@@@ Falta link BLM @@@@</li>
```

2024-09-24 20:57 UTC, enriqueacosta commented on source/gra3-uni4/gra3-uni4-secD-lec20-cool.ptx
> +    <li>Sé que <m>10\times6</m> es 60 y <m>6\times6</m> es <m>36</m>, y <m>60 + 36 = 96</m>. <m>10 + 6=16</m>.</li>
Le faltan `<m>` al 60.

2024-09-24 20:57 UTC, enriqueacosta commented on source/gra3-uni4/gra3-uni4-secD-lec20-act2-mat.ptx
> +<li><xref ref="blm-papelCuadriculadoCentimetro" text="title"/></li>
Genial! :-)

2024-09-25 11:39 UTC, aguilulfo commented on source/gra3-uni4/gra3-uni4-secD-lec20-act3-mat.ptx
> +<li>Compara, Etapa 4 (Tarjetas de división) </li>
DONE! Creo que ok con "@"!

2024-09-25 11:40 UTC, aguilulfo commented on source/gra3-uni4/gra3-uni4-secD-lec20-cool.ptx
> +    <li>Sé que <m>10\times6</m> es 60 y <m>6\times6</m> es <m>36</m>, y <m>60 + 36 = 96</m>. <m>10 + 6=16</m>.</li>
Done!

2024-09-25 17:09 UTC, enriqueacosta commented on source/gra3-uni4/gra3-uni4-secD-lec20-warm.ptx
> +      <q>¿Cómo nos ayuda pensar en la multiplicación cuando dividimos?</q>.</li>
@aguilulfo , ¿acá si va punto?

2024-09-25 17:09 UTC, merged